### ISSUE TITLE
module 'jiwer.transforms' has no attribute 'ReduceToListOfListOfWords'

### ISSUE THREAD

**Issue by adnanammanullah** [jitsi/jiwer#51]
Hi,

I did downloaded this repo as zip and facing following exception after configuring the project, when executing analyzer.py :

**AttributeError: module 'jiwer.transforms' has no attribute 'ReduceToListOfListOfWords'**

**Comment by nikvaessen** [comment]
I don't know what this `analyzer.py` looks like, how you run it, and how you installed the package in your (virtual) environment. Without further information, I would advice you to install the package using either `pip` or `poetry`.

**Comment by adnanammanullah** [comment]
issue created by mistake, please delete this thread. thanks
