### ISSUE TITLE
Avoid error when a string in the truth is empty after transformation

### ISSUE THREAD

**Issue by bdhoore** [jitsi/jiwer#57]
A suggestion to add:
To avoid getting an error message when transforming the truth leads to an empty string, I added the following in _preprocess:
pop the empty string item from the transformed_truth and the transformed_hypothesis.
I found this useful for my purposes. Perhaps others may too.

    # Apply transforms. The transforms should collapses input to a list of list of words
    transformed_truth = truth_transform(truth)
    transformed_hypothesis = hypothesis_transform(hypothesis)
    n=0
    for e in transformed_truth:
        if (len(e) == 0):
           #if truth is empty, remove that item from the list and from the transformed hypotheses
           transformed_truth.pop(n)
           transformed_hypothesis.pop(n)
        n += 1

    # raise an error if the ground truth is empty or the output
    # is not a list of list of strings

**Comment by nikvaessen** [comment]
Also note that `jiwer.RemoveEmptyStrings()` exists for this purpose.
