### ISSUE TITLE
Alignment options similar to `fstalign`

### ISSUE THREAD

**Issue by sreeprasannar** [jitsi/jiwer#58]
[fstalign](https://github.com/revdotcom/fstalign/blob/develop/docs/Advanced-Usage.md) has an `--output-sbs` flag which allows the user to use the alignment for post-processing. I was wondering if `jiwer` has such a flag?

**Comment by nikvaessen** [comment]
The latest version (2.6.0) provides, and can visualize, the alignment between each ground-truth/hypothesis pair.
