### ISSUE TITLE
Batch vs Individual results are not same

### ISSUE THREAD

**Issue by rajeevbaalwan** [jitsi/jiwer#59]
I have tried calculating WER and CER using jiwer in one case I'm running jiwer.wer and jiwer.cer function individually on single (target, prediction) pairs and take the average at the end, and in the other case, I'm passing the whole list of targets and predictions to jiwer.wer and jiwer.cer functions. In both cases, I'm getting different WER and CER with the same set of target and prediction pairs which ideally shouldn't be the case.

Any idea why is this happening?

**Comment by nikvaessen** [comment]
This might be related to https://github.com/jitsi/jiwer/issues/46? Are you using the latest version?

**Comment by rajeevbaalwan** [comment]
I am using version 2.3.0

**Comment by nikvaessen** [comment]
Can you share a minimal example?

**Comment by rajeevbaalwan** [comment]
![Screenshot from 2022-08-18 17-37-33](https://user-images.githubusercontent.com/18329235/185391261-9b834703-7540-41cc-9f1f-d4c2563ad6bb.png)


As you can see WEr and CER is different in both cases.

**Comment by nikvaessen** [comment]
The problem is taking the mean across 2 word-error-rate values is not the same as computing the WER over two sentences.

If you look at the formula of WER:

![image](https://user-images.githubusercontent.com/7225987/188173780-6840d572-3df1-4470-b40c-b10896971031.png)

For your case:

```python
import jiwer

# sentence 1 - 1 substitution, 3 correct
ref0 = "a b c d"
hyp0 = "a b c e"

wer0 = jiwer.wer(ref0, hyp0) # 0.25

# sentence 2 - 1 substitution, 2 correct
ref1 = "ab bc cd"
hyp1 = "ba bc cd"
 
wer1 = jiwer.wer(ref1, hyp1) # 0.33

# manual computation answer
s = 1 + 1
d = 0
i = 0
c = 3 + 2

manual_wer = (s + d + i) / (s + d + c) # 0.2857142857142857
average_wer = (wer0 + wer1) / 2 # 0.29166666666666663

wer = jiwer.wer([ref0, ref1], [hyp0, hyp1]) # 0.2857142857142857
```

**Comment by nikvaessen** [comment]
In practise, the WER is a weighted average, the longer the sentence, the more opportunity for mistakes, etc.
