### ISSUE TITLE
Major performance regression in 2.5.0 for jiwer.transforms.RemovePunctuation

### ISSUE THREAD

**Issue by f4hy** [jitsi/jiwer#66]
There is a major performance regression in jiwer.transforms.RemovePunctuation in 2.5.0
`%timeit jiwer.transforms.RemovePunctuation()` gives `228 ms ± 4.34 ms per loop` on 2.5.0
but
`%timeit jiwer.transforms.RemovePunctuation()` gives `1.35 µs ± 8.61 ns per loop` on 2.4.0
this is `168,888` **times** slower.

I had a pipeline where I was computing the WER both with and without removing punctuation. I was recreating the transform list each time. This can be solved by computing it up front and caching the transformations, but I am very surprised to find this to be the cause of my regression.

**Comment by f4hy** [comment]
Looks like this is caused by `https://github.com/jitsi/jiwer/commit/0fc3893027bcc03114b34e33da5c5298b7da20e1#`

**Comment by nikvaessen** [comment]
Thanks for spotting the issue and making a quick PR!
